version: '3.8'

services:
  app:
    build: .
    ports:
      - "3080:3080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/tetris
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
